branch-defaults:
  beanstalk_test:
    environment: opdash-cp
global:
  application_name: opdash-cp
  branch: null
  default_ec2_keyname: null
  default_platform: Python 3.4
  default_region: us-east-1
  profile: eb-cli
  repository: null
sc: git