---
  # Quick place to check current environment
- ENVIRONMENT: local

  # Env variable to use when looking for an additional configuration
  # EX: use export OPDASH_CP_CONFIG="/some/path/to/file.yml"
- CONFIG_OVERRIDE_ENV_VAR: OPDASH_CP_CONFIG

  # Location where the migrator service is running
- API:
    BASE_URL: http://opdash-api-dev.us-east-1.elasticbeanstalk.com

    # Timeout length for calls to the API (in seconds)
    PROXY_TIMEOUT: 60

- IDENTITY_URL: https://identity-internal.api.rackspacecloud.com/v2.0

- SAML:
    # SAML enablement. Disabled by default
    ENABLED: False

    CONFIG_PATH: ./opdash/saml_config.json

- PILOT:
    # The URL to the pilot API for this environment (prod / staging)
    URL: https://prod.pilot.api.rackspacecloud.com/v1/

    # The product name for this application in PILOT
    PRODUCT: ''  # we don't have a product in the menu yet

    MYCLOUD_URL: https://mycloud.rackspace.com

    # The path Pilot sends the user to for log out in this application
    LOGOUT_URL: /logout

- AWS:
    # AWS credentials with which to connect to resources
    # ACCESS_KEY_ID:
    # SECRET_ACCESS_KEY:

- RAX:
    BILLING:
      - ENDPOINT: https://billingv2.api.rackspacecloud.com/v2

- CACHE:
    # Type of cache to use. Available: filesystem, redis
    TYPE: filesystem

    # Directory to store filesystem cache. Ignored when type is "redis"
    DIR: ./session

    # Host where redis server is listening. Ignored when type is "filesystem"
    # REDIS_HOST: 0.0.0.0

    # Prefix for values stored in redis. Ignored when type is "filesystem"
    # KEY_PREFIX: opdash-session

# Collection of flask specific configuration items. For more information see:
# http://flask.pocoo.org/docs/0.12/config/#builtin-configuration-values
- FLASK:

    # What address to listen to for incoming traffic
    HOST: 0.0.0.0

    # The port to listen to for incoming traffic
    PORT: 8000

    # Run the server in debug mode or not
    # False - Runs the application using a production level waitress WSGI server.
    # True - Runs the application using a non-production level werkzeug server which supports auto-reloading.
    DEBUG: True

    # When DEBUG is true, should werkzeug detect py file changes and reload them.
    USE_RELOADER: True

# If you want to encrypt your config file:
# run python with the current app in path then run:
# opdash_cp.encryption_helper.encrypt_file({key}, {file}[, {out_file}])
# where "key" is the encryption file and "file" is
# the input file. Optionally an output file can be specified.

# To decrypt a file use:
# opdash_api.encryption_helper.decrypt_file({key}, {file}[, {out_file}]).
- ENCRYPTION:
    # Environment variable key used when looking for the decryption key
    # to decrypt an encrypted configuration during local development.
    CONFIG_LOCAL_KEY: DECRYPT_KEY
